name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  update_on_vm:
    name: updating server on digitalocean using ssh
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: 
            git clone ${{ secrets.REPOSITORY_PATH}};
            cd ${{ secrets.FOLDER_NAME }};
            git pull https://${{ secrets.G_USERNAME }}:${{ secrets.G_TOKEN }}@github.com/${{ secrets.G_USERNAME }}/${{ secrets.FOLDER_NAME }}.git;
            pkill -f 'node index.js';
            ulimit -Sn 1048576;
            nohup node index.js > output.log 2>&1 &;
            exit;
